CELDA_LIBRE = 0
CELDA_OBSTACULO = 1
CELDA_MONEDA_5 = 2
CELDA_MONEDA_10 = 3
CELDA_BOMBA = 4
CELDA_FANTASMA = 5


TAMAÑOS = [10, 20, 30]

TIEMPO_INICIAL = 2.0
TIEMPO_AUMENTO_DIFICULTAD = 15.0
DECREMENTO_TIEMPO = 0.1
TIEMPO_MINIMO = 0.2
TIEMPO_APARICION_ELEMENTOS = 2.5
DURACION_ELEMENTOS = 10.0

PORCENTAJE_OBSTACULOS = 0.60
MAX_LIBRES_CONSECUTIVAS = 5

PUNTOS_MONEDA_5 = 5
PUNTOS_MONEDA_10 = 10


DIRECCION_ARRIBA = (-1, 0)
DIRECCION_ABAJO = (1, 0)
DIRECCION_IZQUIERDA = (0, -1)
DIRECCION_DERECHA = (0, 1)

COLOR_FONDO = "#000000"
COLOR_LIBRE = "#FFDE7A"
COLOR_OBSTACULO = "#310901"
COLOR_JUGADOR = "#0000ff"
COLOR_MONEDA_5 = "#ffd700"
COLOR_MONEDA_10 = "#ff8c00"
COLOR_BOMBA = "#ff0000"
COLOR_FANTASMA = "#9370db"
COLOR_TEXTO = "#ffffff"
COLOR_BORDE = "#0f0f0f"
COLOR_TOP_DESTACADO = "#d7b700"

TAMAÑO_CELDA_PX = 28

CARPETA_SONIDOS = "sonidos"
ARCHIVO_FONDO = "fondo.ogg"
ARCHIVO_MONEDA = "moneda.wav"
ARCHIVO_BOMBA = "bomba.wav"
ARCHIVO_FANTASMA = "fantasma.wav"
ARCHIVO_GAME_OVER = "gameover.ogg"
 
VOLUMEN_MUSICA_FONDO = 0.4
VOLUMEN_EFECTOS = 0.8